if (!require("tidyverse"))
  install.packages("tidyverse")
if (!require("shiny"))
  install.packages("shiny")
if (!require("shinyWidgets"))
  install.packages("shinyWidgets")
if (!require("plotly"))
  install.packages("plotly")
if (!require("CatEncoders"))
  install.packages("CatEncoders")
if (!require("randomForest"))
  install.packages("randomForest")

library(shiny)
library(shinyWidgets)
library(plotly)
library(tidyverse)
library(CatEncoders)
library(randomForest)
